window.ITEMS = [
  {
    id: "zipnn",
    title: "ZipNN",
    tag: "Work",
    section: "work",
    status: "active",
    blurb: "Lossless compression built for AI model data.",
    detail: "IBM Research · IEEE CLOUD 2025",
    href: "https://github.com/zipnn/zipnn",
    cover: "images/covers/zipnn.jpg",
    hover: "images/hover/zipnn.jpg",
  },
  {
    id: "klafi",
    title: "Klafi",
    tag: "Game",
    section: "games",
    status: "active",
    blurb: "A collectible card game about Israeli politics.",
    detail: "Independent game · Active",
    href: "https://klafi.vercel.app",
    cover: "images/covers/klafi.jpg",
    hover: "images/hover/klafi.jpg",
  },
  {
    id: "llmd",
    title: "llm-d",
    tag: "Work",
    section: "work",
    status: "active",
    blurb: "Kubernetes-native distributed LLM inference.",
    detail: "IBM Research · Inference systems",
    href: "https://www.llm-d.ai",
    cover: "images/covers/llmd.jpg",
    hover: "images/hover/llmd.jpg",
  },
  {
    id: "holdemle",
    title: "Hold'emle",
    tag: "Game",
    section: "games",
    status: "active",
    blurb: "A daily puzzle about pre-flop poker equity.",
    detail: "Independent game · Daily puzzle",
    href: "https://holdemle.vercel.app",
    cover: "images/covers/holdemle.jpg",
    hover: "images/hover/holdemle.jpg",
  },
  {
    id: "conveyor",
    title: "Conveyor Race",
    tag: "Game",
    section: "games",
    status: "active",
    blurb: "A printable board game about a sabotaged kitchen.",
    detail: "Board game · Print & play",
    href: "https://conveyor-race.vercel.app",
    cover: "images/covers/conveyor.jpg",
    hover: "images/hover/conveyor.jpg",
  },
  {
    id: "skystore",
    title: "SkyStore",
    tag: "Work",
    section: "work",
    status: "active",
    blurb: "A cost-aware object store across multiple clouds.",
    detail: "IBM Research · VLDB 2025",
    href: "https://arxiv.org/abs/2502.20818",
    cover: "images/covers/skystore.jpg",
    hover: "images/hover/skystore.jpg",
  },
  {
    id: "packrat",
    title: "Set Hunter",
    tag: "Game",
    section: "games",
    status: "active",
    blurb: "Collect sets of animals across four biomes.",
    detail: "Independent game · Web",
    href: "https://pack-rat-game.vercel.app",
    cover: "images/covers/packrat.jpg",
    hover: "images/hover/packrat.jpg",
  },
  {
    id: "wc26",
    title: "WC26 Group Bet",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "A private World Cup prediction game for a group.",
    detail: "Community tool · Active",
    href: "https://wc26-group-bet.vercel.app",
    cover: "images/covers/wc26.jpg",
    hover: "images/hover/wc26.jpg",
  },
  {
    id: "u20",
    title: "U20 Manager",
    tag: "Game",
    section: "games",
    status: "active",
    blurb: "A browser basketball management roguelike.",
    detail: "Independent game · Web",
    href: "https://u20-basketball-manager.vercel.app",
    cover: "images/covers/u20.jpg",
    hover: "images/hover/u20.jpg",
  },
  {
    id: "bbfantasy",
    title: "BB U21 Fantasy",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "U21 Israel fantasy basketball and a daily puzzle.",
    detail: "Fantasy tool · Active",
    href: "https://bb-fantasy.vercel.app",
    cover: "images/covers/bbfantasy.jpg",
    hover: "images/hover/bbfantasy.jpg",
  },
  {
    id: "riftrade",
    title: "RifTrade",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "A community swap directory for Riftbound cards.",
    detail: "Riftbound community tool",
    href: "https://rif-trade.vercel.app",
    cover: "images/covers/riftrade.jpg",
    hover: "images/hover/riftrade.jpg",
  },
  {
    id: "gamerev",
    title: "GameRev",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "A personal catalog for ranking and reviewing games.",
    detail: "Personal tool · Active",
    href: "https://game-rev.vercel.app",
    cover: "images/covers/gamerev.jpg",
    hover: "images/hover/gamerev.jpg",
  },
  {
    id: "classmatch",
    title: "Class matching",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "Constraint-based student-to-class assignment.",
    detail: "Optimization tool · Active",
    href: "https://class-matching-nine.vercel.app",
    cover: "images/covers/classmatch.jpg",
    hover: "images/hover/classmatch.jpg",
  },
  {
    id: "boxscore",
    title: "BB Box Score",
    tag: "Project",
    section: "projects",
    status: "active",
    blurb: "Visual shot and box-score analysis for BuzzerBeater.",
    detail: "Basketball analysis tool",
    href: "https://box-score-analysis.vercel.app",
    cover: "images/covers/boxscore.jpg",
    hover: "images/hover/boxscore.jpg",
  },
  {
    id: "rps",
    title: "RPS",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "Slide tiles and score with rock-paper-scissors rules.",
    href: "https://guygir.itch.io/rps",
    cover: "images/covers/rps.jpg",
    hover: "images/hover/rps.jpg",
  },
  {
    id: "arrows",
    title: "Arrow's Theorem",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "Win an election at any cost.",
    href: "https://guygir.itch.io/arrows-theorem",
    cover: "images/covers/arrows.jpg",
    hover: "images/hover/arrows.jpg",
  },
  {
    id: "insecurities",
    title: "Insecurities",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "A game-jam tale of two insecure characters.",
    href: "https://guygir.itch.io/insecurities",
    cover: "images/covers/insecurities.jpg",
    hover: "images/hover/insecurities.jpg",
  },
  {
    id: "wonderful-life",
    title: "Wonderful Life",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "Relive a life through memories on an operating table.",
    href: "https://guygir.itch.io/wonderful-life",
    cover: "images/covers/wonderful-life.jpg",
    hover: "images/hover/wonderful-life.jpg",
  },
  {
    id: "sivan",
    title: "SIVAN",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "The character changes the player, not the game.",
    href: "https://guygir.itch.io/sivan",
    cover: "images/covers/sivan.jpg",
    hover: "images/hover/sivan.jpg",
  },
  {
    id: "xxkiller",
    title: "xxKillerxx's PC",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "Be the PC running someone else's bunny-hunting game.",
    href: "https://guygir.itch.io/xxkillerxxs-pc",
    cover: "images/covers/xxkiller.jpg",
    hover: "images/hover/xxkiller.jpg",
  },
  {
    id: "galaxy",
    title: "Around the Galaxy",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "An early action game about the best pilot in the galaxy.",
    href: "https://guygir.itch.io/around-the-galaxy",
    cover: "images/covers/galaxy.jpg",
    hover: "images/hover/galaxy.jpg",
  },
  {
    id: "emotions",
    title: "Emotions",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "A Club Tech title about reading a face across a room.",
    detail: "Unity · Club Tech · 2023",
    href: "https://github.com/guygir/Emotions",
    cover: "images/covers/emotions.svg",
    hover: "images/hover/emotions.svg",
  },
  {
    id: "matching",
    title: "Matching",
    tag: "Game",
    section: "games",
    status: "archive",
    blurb: "A matching game shipped for Club Tech.",
    detail: "Unity · Club Tech · 2023",
    href: "https://github.com/guygir/Matching",
    cover: "images/covers/matching.svg",
    hover: "images/hover/matching.svg",
  },
  {
    id: "digest",
    title: "AI Daily Digest",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "Personalized AI news from sixteen sources.",
    detail: "Parked aggregator",
    href: "https://github.com/guygir/ai-daily-digest",
    cover: "images/covers/digest.svg",
    hover: "images/hover/digest.svg",
  },
  {
    id: "chores",
    title: "Chores Manager",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "A mobile-friendly tracker for recurring home tasks.",
    detail: "Next.js + Supabase · Parked",
    href: "https://github.com/guygir/chores-manager",
    cover: "images/covers/chores.svg",
    hover: "images/hover/chores.svg",
  },
  {
    id: "japan",
    title: "Japan Travel Planner",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "An AI travel planner for a couple's trip.",
    detail: "13 areas · Parked",
    href: "https://github.com/guygir/japan-travel-planner",
    cover: "images/covers/japan.svg",
    hover: "images/hover/japan.svg",
  },
  {
    id: "seam",
    title: "Seam Carving",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "Content-aware image resizing from a graphics course.",
    detail: "University coursework · 2023",
    href: "https://github.com/guygir/Seam_Carving",
    cover: "images/covers/seam.svg",
    hover: "images/hover/seam.svg",
  },
  {
    id: "people",
    title: "People Analytics",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "A university data-science project on people analytics.",
    detail: "University coursework · 2023",
    href: "https://github.com/guygir/People_Analytics_Data_Science_Project",
    cover: "images/covers/people.svg",
    hover: "images/hover/people.svg",
  },
  {
    id: "hwcheck",
    title: "HW Checker",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "A homework checker for computational models.",
    detail: "University coursework · 2023",
    href: "https://github.com/guygir/Computational_Models_HW_Checker",
    cover: "images/covers/hwcheck.svg",
    hover: "images/hover/hwcheck.svg",
  },
  {
    id: "hrcc",
    title: "HRCC",
    tag: "Project",
    section: "projects",
    status: "archive",
    blurb: "Hospitals–residents matching with consistent couples.",
    detail: "Research files · 2023",
    href: "https://github.com/guygir/HRCC",
    cover: "images/covers/hrcc.svg",
    hover: "images/hover/hrcc.svg",
  },
];
